nome=str(input('DIGITE SEU NOME COMPLETO')).strip()
nome1=nome.split()
print(nome1[len(nome1)-1]) #O LEN VERIFICA O TAMANHO DA QUANTIDADE DE PALAVRAS, O MENOS 1 E PARA IR NA POSICAO DA LISTA, OU SEJA CONTANDO A PARTIR DO 0 FICA -1 O VALOR TOTAL DO LEN